# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8ec1afc6f070aa77042f44c3f48f742f5c95dd16f1376c1c1ed68ef35b9394a8c092bcbf61a9b550d5b28dcfaf07c261995cf4a343e07084b9b7297084deba5c

test:
  secret_key_base: d7225ce6a2fdab15309b86e3b79e385764328c7fdb1e8606d74e547243a8d9f31a2b1ade7216de8500cb638d3656d060bd9710b3dec2f575bb7649ae70a09c24

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
